# Generated by Django 5.1.2 on 2024-10-27 08:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='score',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'restaurant')},
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='review',
        ),
    ]
